### ISSUE TITLE
Cannot find module @JPMorganChase/perspective

### ISSUE THREAD

**Issue by dashaangelova** [insidesherpa/JPMC-tech-task-2-PY3#13]
<img width="629" alt="Screenshot 2019-11-13 at 00 03 14" src="https://user-images.githubusercontent.com/47349724/68721106-44cb2f80-05a9-11ea-8e32-062bcde4042b.png">

Getting this error message for some reason?

**Comment by dashaangelova** [comment]
<img width="567" alt="Screenshot 2019-11-13 at 00 05 48" src="https://user-images.githubusercontent.com/47349724/68721139-5c0a1d00-05a9-11ea-936e-dfa0f49f330c.png">

**Comment by jbf-insidesherpa** [comment]
@dashaangelova your npm install probably encountered some errors. Can you paste the errors you got here?

**Comment by michalgrossberg** [comment]
Hi im facing the same error and you are the npm istall failed due to:
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/michal/opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:611:12)
gyp ERR! System Darwin 18.7.0

I have anaconda on my machine , is that a problem?

**Comment by jbf-insidesherpa** [comment]
@michalgrossberg the potential solution to your problem is discussed here:
https://github.com/insidesherpa/JPMC-tech-task-2-PY3/issues/15#issuecomment-554823461

**Comment by pranaysparihar** [comment]
> Hi im facing the same error and you are the npm istall failed due to:
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: /Users/michal/opt/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack File "", line 1
> gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack at ChildProcess.exithandler (child_process.js:289:12)
> gyp ERR! stack at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack at maybeClose (internal/child_process.js:962:16)
> gyp ERR! stack at Socket.stream.socket.on (internal/child_process.js:381:11)
> gyp ERR! stack at Socket.emit (events.js:182:13)
> gyp ERR! stack at Pipe._handle.close (net.js:611:12)
> gyp ERR! System Darwin 18.7.0
> 
> I have anaconda on my machine, is that a problem?



> <img alt="Screenshot 2019-11-13 at 00 03 14" width="629" src="https://user-images.githubusercontent.com/47349724/68721106-44cb2f80-05a9-11ea-8e32-062bcde4042b.png">
> 
> Getting this error message for some reason?

Did you get it to work??

**Comment by pranaysparihar** [comment]
Did you get it to work??
