### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by remiljw** [insidesherpa/JPMC-tech-task-2-PY3#18]
![bug](https://user-images.githubusercontent.com/39375446/69429011-e03f6b80-0d32-11ea-8d98-12afd6cc3eaa.png)
Server throwing up `dateutil.parser` error despite dateutil been installed

**Comment by remiljw** [comment]
fixed.
Changed Environment variable(Put Python 3.5.2 in my system variable)
Had two python versions(2.7 and 3.5.2)

**Comment by jbf-insidesherpa** [comment]
@remiljw glad you fixed your issue. the solutions around the issues you were experiencing were also discussed in the updated setup guide.

Another way you could've done it was to change the python3.x executable in it's directory as python3.exe and added it into your system path env so that python still maps to 2.7.x and python3 maps to your python 3 version.

However, you must note we've actually found an issue with python 3.5.2. Probably better for you to have a higher python3 version instead, e.g. 3.6 above. (see this issue: https://github.com/insidesherpa/JPMC-tech-task-1-PY3/issues/10#issuecomment-557412872)
