### ISSUE TITLE
Unable to run server.py

### ISSUE THREAD

**Issue by Rakavee** [insidesherpa/JPMC-tech-task-2-PY3#21]
Current Python version : 3.7.4
Running python server.py gives:
python: can't open file 'datafeed/server.py': [Errno 2] No such file or directory

Running python3 server.py gives nothing and goes back to prompt.

**Comment by jbf-insidesherpa** [comment]
@Rakavee that's because the server script in this repo (which is the python 3 repo for task 2) is not named server.py, but instead it's server3.py. So in your case, if you're in the root folder of the repository in your commandline, you should execute
`python3 datafeed/server3.py`

> Running python3 server.py gives nothing and goes back to prompt.
Can you post a screenshot of the output on your command line for `python --version` and the output for `python3 --version`

**Comment by Rakavee** [comment]
Right. Not sure how I missed that. Thanks.
