### ISSUE TITLE
Graph not showing

### ISSUE THREAD

**Issue by neissacodes** [insidesherpa/JPMC-tech-task-2-PY3#30]
After editing both Graph and App files, when I click on streaming data the server receives the queries but the graph does not show at all. 
![JPMCtask21](https://user-images.githubusercontent.com/47401355/72241339-99dcef00-35b4-11ea-8133-b2b016cb09a3.PNG)

**Comment by neissacodes** [comment]
With an error like this one.
![jpmc](https://user-images.githubusercontent.com/47401355/72273510-7471d480-35f8-11ea-8799-20e3c9dc8212.PNG)

**Comment by jbf-insidesherpa** [comment]
@neissacodes the error you got in the last screenshot is just the data re-initializing, i.e. it just went back to 2019. So that shouldn't be a problem.

From what it looks like, your server is getting the requests from the client but the client isn't successfully rendering the graph. Probably best if you put some logs in the render / update functions in Graph.tsx to see if it's getting the data.

Also, just to check did you successfully finish the setup? i.e. did you see the initial table where you had to keep on clicking the blue button to show new data?

**Comment by neissacodes** [comment]
Yes, I saw the initial table with the data. 
Will do, thank you.

**Comment by slbae** [comment]
I am having this same problem and I added logs in Graph.tsx and they didn't print to the console. I followed all the set up correctly too.
