### ISSUE TITLE
npm start isn't working, couldn't jump to web page 

### ISSUE THREAD

**Issue by HenryChoi1999** [insidesherpa/JPMC-tech-task-2-PY3#8]
<img width="1104" alt="Screenshot 2019-11-07 at 5 41 07 PM" src="https://user-images.githubusercontent.com/57482903/68377835-089d6680-0186-11ea-99de-feb2de1c91e7.png">

**Comment by jbf-insidesherpa** [comment]
@HenryChoi1999 the reason it's not working for you is because you're terminal's current working directory isn't inside the repository you cloned. You need to **cd** into the repository first, like:
`cd JPMC-tech-task-2-PY3` if you cloned it from ~ (aka home dir)

also before you run `npm start` you should run `npm install` inside the repository first too.
